<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>TecladoConMouse</AssemblyName>
    <RootNamespace>TecladoConMouse</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <NoWarn>$(NoWarn);WFO0003</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Datos\es_50k.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
